# Generated by Django 5.2.5 on 2025-08-16 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('equipment_required', models.TextField(blank=True, null=True)),
                ('sample_preparation', models.TextField(blank=True, null=True)),
                ('typical_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analysis_methods',
                'ordering': ['method_name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('composition', models.TextField(blank=True, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('applications', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'material_types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='MeteoriteClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('discovered_date', models.DateField(blank=True, null=True)),
                ('mass_g', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'meteorite_classifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProteinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=20, unique=True)),
                ('uniprot_id', models.CharField(max_length=20)),
                ('protein_name', models.CharField(max_length=200)),
                ('organism', models.CharField(max_length=100)),
                ('sequence_length', models.IntegerField()),
                ('structure_method', models.CharField(max_length=50)),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('doi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'protein_data',
                'ordering': ['pdb_id'],
            },
        ),
        migrations.CreateModel(
            name='MeteoriteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('official_name', models.CharField(max_length=100)),
                ('alternative_names', models.TextField(blank=True, null=True)),
                ('discovery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('fall_date', models.DateField(blank=True, null=True)),
                ('total_known_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astro_data.meteoriteclassification')),
            ],
            options={
                'db_table': 'meteorite_names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AstroData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('research_date', models.DateField(blank=True, null=True)),
                ('researcher', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astro_data.analysismethod')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astro_data.materialtype')),
                ('meteorite_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astro_data.meteoriteclassification')),
                ('meteorite_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astro_data.meteoritename')),
            ],
            options={
                'db_table': 'astro_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
