# Generated by Django 5.2 on 2025-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astrodata',
            name='analysis_method',
        ),
        migrations.RemoveField(
            model_name='astrodata',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='astrodata',
            name='meteorite_classification',
        ),
        migrations.RemoveField(
            model_name='astrodata',
            name='meteorite_name',
        ),
        migrations.RemoveField(
            model_name='meteoritename',
            name='classification',
        ),
        migrations.DeleteModel(
            name='AnalysisMethod',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.DeleteModel(
            name='AstroData',
        ),
        migrations.DeleteModel(
            name='MeteoriteName',
        ),
    ]
