# Generated by Django 5.2.1 on 2025-09-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meteorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("classification", models.CharField(db_index=True, max_length=50)),
                (
                    "discovery_location",
                    models.CharField(db_index=True, default="Unknown", max_length=100),
                ),
                ("origin", models.CharField(db_index=True, max_length=50)),
                ("organic_compounds", models.JSONField(blank=True, default=list)),
                ("contamination_exclusion_method", models.TextField(blank=True)),
                ("references", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "meteorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "classification"],
                        name="meteorites_name_11aa8b_idx",
                    ),
                    models.Index(
                        fields=["origin", "classification"],
                        name="meteorites_origin_e0aff0_idx",
                    ),
                    models.Index(
                        fields=["discovery_location", "origin"],
                        name="meteorites_discove_205856_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="meteorites_created_429806_idx"
                    ),
                ],
            },
        ),
    ]
