# Generated by Django 5.2.1 on 2025-09-27 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExtractionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("single_document", "单文档提取"),
                            ("batch_documents", "批量文档提取"),
                            ("query_based", "基于查询的提取"),
                        ],
                        max_length=30,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="任务参数")),
                ("results", models.JSONField(default=dict, verbose_name="执行结果")),
                (
                    "total_documents",
                    models.IntegerField(default=0, verbose_name="总文档数"),
                ),
                (
                    "processed_documents",
                    models.IntegerField(default=0, verbose_name="已处理文档数"),
                ),
                (
                    "successful_extractions",
                    models.IntegerField(default=0, verbose_name="成功提取数"),
                ),
                (
                    "failed_extractions",
                    models.IntegerField(default=0, verbose_name="失败提取数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "数据提取任务",
                "verbose_name_plural": "数据提取任务",
                "db_table": "data_extraction_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeteoriteReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "提交审核"),
                            ("approved", "批准"),
                            ("rejected", "拒绝"),
                            ("revision_requested", "要求修订"),
                            ("resubmitted", "重新提交"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(max_length=20, verbose_name="之前状态"),
                ),
                ("new_status", models.CharField(max_length=20, verbose_name="新状态")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "review_details",
                    models.JSONField(
                        default=dict,
                        help_text="详细的审核信息和建议",
                        verbose_name="审核详情",
                    ),
                ),
            ],
            options={
                "verbose_name": "陨石审核日志",
                "verbose_name_plural": "陨石审核日志",
                "db_table": "meteorite_review_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="meteorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "陨石",
                "verbose_name_plural": "陨石",
            },
        ),
        migrations.RemoveIndex(
            model_name="meteorite",
            name="meteorites_name_11aa8b_idx",
        ),
        migrations.RemoveIndex(
            model_name="meteorite",
            name="meteorites_origin_e0aff0_idx",
        ),
        migrations.RemoveIndex(
            model_name="meteorite",
            name="meteorites_discove_205856_idx",
        ),
        migrations.AddField(
            model_name="meteorite",
            name="confidence_score",
            field=models.FloatField(
                default=0.0,
                help_text="数据提取和验证的置信度分数 (0.0-1.0)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="置信度分数",
            ),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="extraction_metadata",
            field=models.JSONField(
                default=dict,
                help_text="数据提取过程的详细信息",
                verbose_name="提取元数据",
            ),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="extraction_source",
            field=models.CharField(
                choices=[
                    ("manual", "手动录入"),
                    ("rag_extraction", "RAG自动提取"),
                    ("import", "批量导入"),
                ],
                default="manual",
                max_length=50,
                verbose_name="数据来源",
            ),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="review_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核日期"),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="review_notes",
            field=models.TextField(
                blank=True, help_text="审核人员的备注和建议", verbose_name="审核备注"
            ),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已批准"),
                    ("rejected", "已拒绝"),
                    ("needs_revision", "需要修订"),
                ],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="meteorite",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_meteorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="classification",
            field=models.CharField(
                help_text="陨石的科学分类", max_length=100, verbose_name="分类"
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="contamination_exclusion_method",
            field=models.TextField(
                help_text="用于排除地球污染的方法和程序", verbose_name="污染排除方法"
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="discovery_location",
            field=models.CharField(
                help_text="陨石的发现或收集地点",
                max_length=300,
                verbose_name="发现地点",
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="name",
            field=models.CharField(
                help_text="陨石的官方名称或编号",
                max_length=200,
                verbose_name="陨石名称",
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="organic_compounds",
            field=models.JSONField(
                default=dict,
                help_text="检测到的有机化合物详细信息",
                verbose_name="有机化合物",
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="origin",
            field=models.CharField(
                help_text="推测的母体来源", max_length=200, verbose_name="来源"
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="references",
            field=models.JSONField(
                default=list, help_text="相关的科学文献引用", verbose_name="参考文献"
            ),
        ),
        migrations.AlterField(
            model_name="meteorite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(fields=["name"], name="meteorites_name_64af37_idx"),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["classification"], name="meteorites_classif_4d3073_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["discovery_location"], name="meteorites_discove_c49cf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(fields=["origin"], name="meteorites_origin_30ac2a_idx"),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["review_status"], name="meteorites_review__62b065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["extraction_source"], name="meteorites_extract_df9685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["is_active"], name="meteorites_is_acti_0cb0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["review_status", "created_at"],
                name="meteorites_review__33fd3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meteorite",
            index=models.Index(
                fields=["extraction_source", "review_status"],
                name="meteorites_extract_5e04bc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="meteorite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)
                ),
                name="valid_confidence_score",
            ),
        ),
        migrations.AddField(
            model_name="dataextractiontask",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="meteoritereviewlog",
            name="meteorite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_logs",
                to="meteorite_search.meteorite",
                verbose_name="陨石",
            ),
        ),
        migrations.AddField(
            model_name="meteoritereviewlog",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddIndex(
            model_name="dataextractiontask",
            index=models.Index(fields=["status"], name="data_extrac_status_7f540c_idx"),
        ),
        migrations.AddIndex(
            model_name="dataextractiontask",
            index=models.Index(
                fields=["task_type"], name="data_extrac_task_ty_b1a082_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataextractiontask",
            index=models.Index(
                fields=["created_by"], name="data_extrac_created_70549b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataextractiontask",
            index=models.Index(
                fields=["created_at"], name="data_extrac_created_47a468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlog",
            index=models.Index(
                fields=["meteorite", "timestamp"], name="meteorite_r_meteori_72e300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlog",
            index=models.Index(
                fields=["reviewer", "timestamp"], name="meteorite_r_reviewe_c26164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlog",
            index=models.Index(fields=["action"], name="meteorite_r_action_42c856_idx"),
        ),
    ]
