# Generated by Django 5.2.1 on 2025-09-27 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0002_dataextractiontask_meteoritereviewlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedMeteorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="陨石的官方名称或编号",
                        max_length=200,
                        verbose_name="陨石名称",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        help_text="陨石的科学分类", max_length=100, verbose_name="分类"
                    ),
                ),
                (
                    "discovery_location",
                    models.CharField(
                        help_text="陨石的发现或收集地点",
                        max_length=300,
                        verbose_name="发现地点",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="推测的母体来源", max_length=200, verbose_name="来源"
                    ),
                ),
                (
                    "organic_compounds",
                    models.JSONField(
                        default=dict,
                        help_text="检测到的有机化合物详细信息",
                        verbose_name="有机化合物",
                    ),
                ),
                (
                    "contamination_exclusion_method",
                    models.TextField(
                        help_text="用于排除地球污染的方法和程序",
                        verbose_name="污染排除方法",
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        default=list,
                        help_text="相关的科学文献引用",
                        verbose_name="参考文献",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="AI提取数据的置信度评分 (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="置信度分数",
                    ),
                ),
                (
                    "extraction_source",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("manual", "手动输入"),
                            ("api", "API导入"),
                            ("batch", "批量导入"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "extraction_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="数据提取过程的详细信息",
                        verbose_name="提取元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="批准时间"),
                ),
                (
                    "original_pending_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="原始待审核ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_meteorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "已批准陨石",
                "verbose_name_plural": "已批准陨石",
                "db_table": "approved_meteorites",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingMeteorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="陨石的官方名称或编号",
                        max_length=200,
                        verbose_name="陨石名称",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        help_text="陨石的科学分类", max_length=100, verbose_name="分类"
                    ),
                ),
                (
                    "discovery_location",
                    models.CharField(
                        help_text="陨石的发现或收集地点",
                        max_length=300,
                        verbose_name="发现地点",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="推测的母体来源", max_length=200, verbose_name="来源"
                    ),
                ),
                (
                    "organic_compounds",
                    models.JSONField(
                        default=dict,
                        help_text="检测到的有机化合物详细信息",
                        verbose_name="有机化合物",
                    ),
                ),
                (
                    "contamination_exclusion_method",
                    models.TextField(
                        help_text="用于排除地球污染的方法和程序",
                        verbose_name="污染排除方法",
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        default=list,
                        help_text="相关的科学文献引用",
                        verbose_name="参考文献",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="AI提取数据的置信度评分 (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="置信度分数",
                    ),
                ),
                (
                    "extraction_source",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("manual", "手动输入"),
                            ("api", "API导入"),
                            ("batch", "批量导入"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "extraction_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="数据提取过程的详细信息",
                        verbose_name="提取元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("under_review", "审核中"),
                            ("needs_revision", "需要修订"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="审核人员的备注和建议",
                        verbose_name="审核备注",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "低优先级"),
                            (2, "中优先级"),
                            (3, "高优先级"),
                            (4, "紧急"),
                        ],
                        default=1,
                        verbose_name="审核优先级",
                    ),
                ),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_pending_meteorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="指定审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "待审核陨石",
                "verbose_name_plural": "待审核陨石",
                "db_table": "pending_meteorites",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RejectedMeteorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="陨石的官方名称或编号",
                        max_length=200,
                        verbose_name="陨石名称",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        help_text="陨石的科学分类", max_length=100, verbose_name="分类"
                    ),
                ),
                (
                    "discovery_location",
                    models.CharField(
                        help_text="陨石的发现或收集地点",
                        max_length=300,
                        verbose_name="发现地点",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="推测的母体来源", max_length=200, verbose_name="来源"
                    ),
                ),
                (
                    "organic_compounds",
                    models.JSONField(
                        default=dict,
                        help_text="检测到的有机化合物详细信息",
                        verbose_name="有机化合物",
                    ),
                ),
                (
                    "contamination_exclusion_method",
                    models.TextField(
                        help_text="用于排除地球污染的方法和程序",
                        verbose_name="污染排除方法",
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        default=list,
                        help_text="相关的科学文献引用",
                        verbose_name="参考文献",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="AI提取数据的置信度评分 (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="置信度分数",
                    ),
                ),
                (
                    "extraction_source",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF文档"),
                            ("manual", "手动输入"),
                            ("api", "API导入"),
                            ("batch", "批量导入"),
                        ],
                        default="pdf",
                        max_length=20,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "extraction_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="数据提取过程的详细信息",
                        verbose_name="提取元数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="拒绝时间"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        help_text="详细说明拒绝的原因", verbose_name="拒绝原因"
                    ),
                ),
                (
                    "rejection_category",
                    models.CharField(
                        choices=[
                            ("data_quality", "数据质量问题"),
                            ("incomplete_info", "信息不完整"),
                            ("duplicate", "重复数据"),
                            ("invalid_classification", "分类错误"),
                            ("contamination_concern", "污染问题"),
                            ("reference_issue", "参考文献问题"),
                            ("other", "其他原因"),
                        ],
                        default="data_quality",
                        max_length=50,
                        verbose_name="拒绝类别",
                    ),
                ),
                (
                    "original_pending_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="原始待审核ID"
                    ),
                ),
                (
                    "can_restore",
                    models.BooleanField(
                        default=True,
                        help_text="是否允许从回收站恢复此数据",
                        verbose_name="可恢复",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_meteorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "回收站陨石",
                "verbose_name_plural": "回收站陨石",
                "db_table": "rejected_meteorites",
                "ordering": ["-rejected_at"],
            },
        ),
        migrations.CreateModel(
            name="MeteoriteReviewLogNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "提交审核"),
                            ("assigned", "分配审核人"),
                            ("started_review", "开始审核"),
                            ("approved", "批准"),
                            ("rejected", "拒绝"),
                            ("revision_requested", "要求修订"),
                            ("resubmitted", "重新提交"),
                            ("restored", "从回收站恢复"),
                            ("permanently_deleted", "永久删除"),
                        ],
                        max_length=30,
                        verbose_name="操作",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(max_length=30, verbose_name="之前状态"),
                ),
                ("new_status", models.CharField(max_length=30, verbose_name="新状态")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "review_details",
                    models.JSONField(
                        default=dict,
                        help_text="详细的审核信息和建议",
                        verbose_name="审核详情",
                    ),
                ),
                (
                    "approved_meteorite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="meteorite_search.approvedmeteorite",
                        verbose_name="已批准陨石",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "pending_meteorite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="meteorite_search.pendingmeteorite",
                        verbose_name="待审核陨石",
                    ),
                ),
                (
                    "rejected_meteorite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="meteorite_search.rejectedmeteorite",
                        verbose_name="回收站陨石",
                    ),
                ),
            ],
            options={
                "verbose_name": "陨石审核日志",
                "verbose_name_plural": "陨石审核日志",
                "db_table": "meteorite_review_logs_new",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(fields=["name"], name="approved_me_name_d6b222_idx"),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(
                fields=["classification"], name="approved_me_classif_0053a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(
                fields=["discovery_location"], name="approved_me_discove_93f9cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(fields=["origin"], name="approved_me_origin_58a4f8_idx"),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(
                fields=["reviewer"], name="approved_me_reviewe_b7f32b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(
                fields=["approved_at"], name="approved_me_approve_34e159_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvedmeteorite",
            index=models.Index(
                fields=["is_active"], name="approved_me_is_acti_7d9eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingmeteorite",
            index=models.Index(
                fields=["review_status"], name="pending_met_review__bee0cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingmeteorite",
            index=models.Index(
                fields=["assigned_reviewer"], name="pending_met_assigne_26822c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingmeteorite",
            index=models.Index(
                fields=["priority", "created_at"], name="pending_met_priorit_1c6e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingmeteorite",
            index=models.Index(
                fields=["confidence_score"], name="pending_met_confide_82e478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingmeteorite",
            index=models.Index(
                fields=["extraction_source"], name="pending_met_extract_ead856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectedmeteorite",
            index=models.Index(
                fields=["reviewer"], name="rejected_me_reviewe_0cbe2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectedmeteorite",
            index=models.Index(
                fields=["rejected_at"], name="rejected_me_rejecte_d9fcb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectedmeteorite",
            index=models.Index(
                fields=["rejection_category"], name="rejected_me_rejecti_90ec2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rejectedmeteorite",
            index=models.Index(
                fields=["can_restore"], name="rejected_me_can_res_d6f767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlognew",
            index=models.Index(
                fields=["pending_meteorite", "timestamp"],
                name="meteorite_r_pending_bf247c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlognew",
            index=models.Index(
                fields=["approved_meteorite", "timestamp"],
                name="meteorite_r_approve_8362c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlognew",
            index=models.Index(
                fields=["rejected_meteorite", "timestamp"],
                name="meteorite_r_rejecte_6c0aab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlognew",
            index=models.Index(
                fields=["reviewer", "timestamp"], name="meteorite_r_reviewe_1c4ff8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meteoritereviewlognew",
            index=models.Index(fields=["action"], name="meteorite_r_action_636df7_idx"),
        ),
    ]
