# Generated by Django 5.2.1 on 2025-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meteorite_search",
            "0003_approvedmeteorite_pendingmeteorite_rejectedmeteorite_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvedmeteorite",
            name="extraction_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="数据提取过程的详细信息",
                verbose_name="提取元数据",
            ),
        ),
        migrations.AlterField(
            model_name="approvedmeteorite",
            name="organic_compounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="检测到的有机化合物详细信息",
                verbose_name="有机化合物",
            ),
        ),
        migrations.AlterField(
            model_name="pendingmeteorite",
            name="extraction_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="数据提取过程的详细信息",
                verbose_name="提取元数据",
            ),
        ),
        migrations.AlterField(
            model_name="pendingmeteorite",
            name="organic_compounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="检测到的有机化合物详细信息",
                verbose_name="有机化合物",
            ),
        ),
        migrations.AlterField(
            model_name="rejectedmeteorite",
            name="extraction_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="数据提取过程的详细信息",
                verbose_name="提取元数据",
            ),
        ),
        migrations.AlterField(
            model_name="rejectedmeteorite",
            name="organic_compounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="检测到的有机化合物详细信息",
                verbose_name="有机化合物",
            ),
        ),
    ]
