# Generated by Django 5.2.1 on 2025-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meteorite_search",
            "0004_alter_approvedmeteorite_extraction_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rejectedmeteorite",
            name="rejection_category",
            field=models.CharField(
                choices=[
                    ("data_quality", "数据质量问题"),
                    ("incomplete_info", "信息不完整"),
                    ("duplicate", "重复数据"),
                    ("invalid_classification", "分类错误"),
                    ("contamination_concern", "污染问题"),
                    ("reference_issue", "参考文献问题"),
                    ("user_deleted", "用户删除"),
                    ("other", "其他原因"),
                ],
                default="data_quality",
                max_length=50,
                verbose_name="拒绝类别",
            ),
        ),
    ]
