# Generated by Django 5.2.1 on 2025-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0006_allow_null_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataextractiontask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("paused", "已暂停"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
