# Generated by Django 5.2.1 on 2025-10-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0007_alter_dataextractiontask_status"),
    ]

    operations = []
