# Generated by Django 5.2.1 on 2025-11-01 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0009_alter_approvedmeteorite_classification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentExtractionTask",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("threshold", models.FloatField(default=0.5)),
                ("sort_by", models.CharField(default="score_desc", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("failed", "失败"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "片段提取会话",
                "verbose_name_plural": "片段提取会话",
                "db_table": "segment_extraction_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_id", models.CharField(max_length=128)),
                ("document_id", models.CharField(max_length=255)),
                ("chunk_index", models.IntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("score", models.FloatField(default=0.0)),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "进行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("order_index", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="meteorite_search.segmentextractiontask",
                    ),
                ),
            ],
            options={
                "verbose_name": "片段提取记录",
                "verbose_name_plural": "片段提取记录",
                "db_table": "segment_extractions",
                "ordering": ["order_index", "requested_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "status"], name="segment_ext_task_id_66516f_idx"
                    ),
                    models.Index(
                        fields=["document_id", "chunk_index"],
                        name="segment_ext_documen_b50e51_idx",
                    ),
                    models.Index(
                        fields=["status", "order_index"],
                        name="segment_ext_status_000345_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "document_id", "chunk_index"),
                        name="unique_segment_per_task",
                    )
                ],
            },
        ),
    ]
