# Generated by Django 5.2.1 on 2025-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteorite_search", "0010_segmentextractiontask_segmentextraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleTaskExtractionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="搜索关键词")),
                (
                    "threshold",
                    models.FloatField(default=0.5, verbose_name="相关性阈值"),
                ),
                (
                    "sort_by",
                    models.CharField(
                        default="score_desc", max_length=20, verbose_name="排序方式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="searching", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "segments_data",
                    models.JSONField(default=dict, verbose_name="片段数据"),
                ),
                (
                    "segment_order",
                    models.JSONField(default=list, verbose_name="片段顺序"),
                ),
                ("queue_data", models.JSONField(default=dict, verbose_name="队列数据")),
                (
                    "aggregated_results",
                    models.JSONField(default=dict, verbose_name="聚合结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "单任务提取会话",
                "verbose_name_plural": "单任务提取会话",
                "db_table": "single_task_extraction_sessions",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="single_task_session_592861_idx"
                    ),
                    models.Index(
                        fields=["status"], name="single_task_status_106b7f_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="single_task_last_up_3c0c56_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="single_task_expires_18c6ba_idx"
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="SegmentExtraction",
        ),
        migrations.DeleteModel(
            name="SegmentExtractionTask",
        ),
    ]
