# Generated by Django 5.2 on 2025-09-07 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True, help_text='作者列表，用逗号分隔', null=True)),
                ('year', models.IntegerField(blank=True, help_text='发表年份', null=True)),
                ('journal', models.CharField(blank=True, help_text='期刊名称', max_length=200, null=True)),
                ('doi', models.CharField(blank=True, help_text='DOI编号', max_length=100, null=True)),
                ('file_path', models.CharField(max_length=1000)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('category', models.CharField(default='未分类', max_length=100)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pdf_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('chunk_index', models.IntegerField()),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pdf_processor.pdfdocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document', 'page_number', 'chunk_index'],
            },
        ),
    ]
