# Generated by Django 5.2 on 2025-09-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0001_initial'),
    ]

    operations = [
    ]
