# Generated by Django 5.2 on 2025-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0002_auto_20250908_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='rag_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
