# Generated by Django 5.2 on 2025-09-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0003_pdfdocument_rag_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='sha1',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
