# Generated by Django 5.2 on 2025-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0004_pdfdocument_sha1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['upload_date'], name='pdf_doc_upload_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['processed'], name='pdf_doc_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['category'], name='pdf_doc_category_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['filename'], name='pdf_doc_filename_idx'),
        ),
    ]
