# Generated by Django 5.2.1 on 2025-10-23 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_processor", "0005_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_path",
                    models.CharField(max_length=500, verbose_name="文档路径"),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="文档标题"
                    ),
                ),
                ("processing_time", models.FloatField(verbose_name="处理时间(秒)")),
                ("confidence_score", models.FloatField(verbose_name="置信度分数")),
                (
                    "meteorite_data",
                    models.JSONField(default=dict, verbose_name="陨石数据"),
                ),
                (
                    "organic_compounds",
                    models.JSONField(default=dict, verbose_name="有机化合物数据"),
                ),
                (
                    "mineral_relationships",
                    models.JSONField(default=dict, verbose_name="矿物关系数据"),
                ),
                (
                    "scientific_insights",
                    models.JSONField(default=dict, verbose_name="科学洞察数据"),
                ),
                (
                    "validation_checks",
                    models.JSONField(default=list, verbose_name="验证检查结果"),
                ),
                (
                    "validation_notes",
                    models.TextField(blank=True, verbose_name="验证说明"),
                ),
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="任务ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="completed", max_length=20, verbose_name="处理状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "直接处理结果",
                "verbose_name_plural": "直接处理结果",
                "db_table": "direct_processing_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
