# Generated by Django 5.2.1 on 2025-10-23 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_processor", "0006_directprocessingresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="任务ID",
                    ),
                ),
                (
                    "document_path",
                    models.CharField(max_length=500, verbose_name="文档路径"),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="文档标题"
                    ),
                ),
                ("options", models.JSONField(default=dict, verbose_name="处理选项")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="处理状态"
                    ),
                ),
                ("progress", models.FloatField(default=0.0, verbose_name="处理进度")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="当前步骤"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理任务",
                "verbose_name_plural": "处理任务",
                "db_table": "processing_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "调试"),
                            ("INFO", "信息"),
                            ("WARNING", "警告"),
                            ("ERROR", "错误"),
                        ],
                        default="INFO",
                        max_length=20,
                        verbose_name="日志级别",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志消息")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="pdf_processor.processingtask",
                        verbose_name="处理任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "处理日志",
                "verbose_name_plural": "处理日志",
                "db_table": "processing_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
